export const ANIMATION_TYPES = {
  COMPARE: "COMPARE",
  SWAP: "SWAP",
  OVERWRITE: "OVERWRITE",
  MARK_SORTED: "MARK_SORTED",
  HIGHLIGHT_RANGE: "HIGHLIGHT_RANGE",
  HIGHLIGHT_PIVOT: "HIGHLIGHT_PIVOT"
};
